# Generated by Django 5.2.10 on 2026-02-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_articlelike_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('article', 'Article'), ('update', 'Project Update'), ('event', 'Event'), ('news', 'News')], db_index=True, default='article', help_text='Type of article content', max_length=20),
        ),
    ]
